# Generated by Django 3.2.4 on 2021-09-16 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('librarian_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'librarians',
            },
            managers=[
                ('librarians', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('registration_number', models.CharField(max_length=150)),
                ('standard', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'students',
            },
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Loan_book',
            fields=[
                ('nam_book_borrowed_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_book_borrowed', models.CharField(max_length=150)),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('date_return', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=150)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.student')),
            ],
            options={
                'db_table': 'loan_books',
            },
            managers=[
                ('loan_books', django.db.models.manager.Manager()),
            ],
        ),
    ]
